title: "Daniel Lokas â€“ AP Networking Portfolio"
description: "AP Networking projects: Silent Signals, Metal to Magic, Component Song"
baseurl: "https://dlokas159.github.io/Lokas-Daniel-Portfolio/"   
url: "https://<dlokas159>.github.io"  
theme: jekyll-theme-hacker
